#
# The NPM certificate from ubuntu/2014.04 is now expired which 
# makes it untrusted. To avoid it freaking out and failing we 
# set the strict-ssl to false here.
#
# Also 2014 ships with v0.10 nodejs, we need something like 4.9.1
# so we put in nvm here to make it happy.
#
$script = <<-SCRIPT
cd /vagrant/v3.3.2
sudo apt update
sudo apt -y install zip build-essential zlib1g-dev libssl-dev nodejs npm 
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
source ~/.bashrc
nvm install v4.9.1
npm config set strict-ssl false
npm install
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest_ip: "127.0.0.1", guest: 9001, host: 9005, host_ip: "127.0.0.1", id: "bsfw"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../", "/vagrant"
end
