$script = <<-SCRIPT
cd /vagrant/v4.4.1
sudo apt update

## These have to be separated, otherwise there's an apt dependency error
sudo apt -y install build-essential zlib1g-dev libssl-dev ruby ruby-dev ruby-bundler nodejs openjdk-17-jre
sudo apt -y install npm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
source ~/.bashrc

nvm install v10.24.1
bundle install
npm install
cd ../
# This higher level one has to exist here to satisfy the fonts and svg creation
npm install

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.insert_key = false
  # config.vm.network "forwarded_port", guest_ip: "127.0.0.1", guest: 9001, host: 9002, host_ip: "127.0.0.1", id: "bsfw"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../", "/vagrant"
end
